$(document).ready(function(){
$("#fadeNapravleniya").fadeOut();
$("#fadeNowosti").fadeOut();
$("#fadeKontakty").fadeOut();
$("#fadeSobytiya").fadeOut();
$("#fadeLichnyyKabinet").fadeOut();
$("span").eq(0).click(function(){
$("#fadeGlavnaya").fadeIn();
$("#fadeNapravleniya").fadeOut();
$("#fadeNowosti").fadeOut();
$("#fadeKontakty").fadeOut();
$("#fadeSobytiya").fadeOut();
$("#fadeLichnyyKabinet").fadeOut();
});
$("span").eq(1).click(function(){
$("#fadeNapravleniya").fadeIn();
$("#fadeGlavnaya").fadeOut();
$("#fadeNowosti").fadeOut();
$("#fadeKontakty").fadeOut();
$("#fadeSobytiya").fadeOut();
$("#fadeLichnyyKabinet").fadeOut();
});
$("span").eq(2).click(function(){
$("#fadeNowosti").fadeIn();
$("#fadeGlavnaya").fadeOut();
$("#fadeNapravleniya").fadeOut();
$("#fadeKontakty").fadeOut();
$("#fadeSobytiya").fadeOut();
$("#fadeLichnyyKabinet").fadeOut();
});
$("span").eq(3).click(function(){
$("#fadeKontakty").fadeIn();
$("#fadeGlavnaya").fadeOut();
$("#fadeNapravleniya").fadeOut();
$("#fadeNowosti").fadeOut();
$("#fadeSobytiya").fadeOut();
$("#fadeLichnyyKabinet").fadeOut();
});
$("span").eq(4).click(function(){
$("#fadeSobytiya").fadeIn();
$("#fadeGlavnaya").fadeOut();
$("#fadeNapravleniya").fadeOut();
$("#fadeNowosti").fadeOut();
$("#fadeKontakty").fadeOut();
$("#fadeLichnyyKabinet").fadeOut();
});
$("span").eq(5).click(function(){
$("#fadeLichnyyKabinet").fadeIn();
$("#fadeGlavnaya").fadeOut();
$("#fadeNapravleniya").fadeOut();
$("#fadeNowosti").fadeOut();
$("#fadeKontakty").fadeOut();
$("#fadeSobytiya").fadeOut();
});
});